### ISSUE TITLE
Create standard for control parsing

### ISSUE THREAD

**Issue by carlosmmatos** [carlosmmatos/automate-compliance#4]
Figure out a way to convert the control id's in the spreadsheet to OpenControl. I May need to modify the spreadsheet as a last resort, but hopefully, we won't have to.

Here is what these controls can look like in their different formats:

Control Structure | Description
------------------|------------
SI-17 | This is a main control
PM-1a. | This is a main control with sub-control (a). Controls can have a..z sub-controls.
PM-1a.1. | Sub-controls can even have more sub-controls PM-1<a..z>.<1..n>. * This is the last breakdown for controls. There are no more <sub> for controls at this point
AC-3 (3) | This is main control AC-3 with control-enhancement (3)
AC-3 (3)(b) | Example sub-control (b) for AC-3 (3)
AC-3 (3)(b)(1) | Furtherst breakdown you can have for control-enhancements

**Comment by JAORMX** [comment]
@carlosmmatos my initial take on this is https://github.com/carlosmmatos/automate-compliance/pull/5 what do you think?
